### PR TITLE
Add a factory to obtain a MustacheEngine instance

### PR DESCRIPTION
**Pull request by mschneid**
This is an attempt to get rid of the cyclic dependency between 'MustacheEngine' and 'MustacheEngineBuilder'.

### CODE REVIEW

**Comment by mkouba** [comment]
-10 for this pull request. I think there is no need to share/cache the default engine instance.

**Comment by mkouba** [comment]
@mschneid Could you elaborate more on the real problems coming from the "cyclic dependency"?

**Comment by mschneid** [comment]
Sorry, wrong button

**Comment by mschneid** [comment]
@mkouba For me it's a design principle that an interface is loose coupled to its concrete implementations. Code quality tools like [SonarQube](https://www.sonarqube.org/) labels such "issues" as *code smells*.

**Comment by mkouba** [comment]
Ok, I'm going to revert https://github.com/trimou/trimou/commit/7a8a7ef9dd88ea895c3f82ec1bea78491719d624 and https://github.com/trimou/trimou/commit/f29e57ab8765fa096850006af387862729070b3b and close this PR. Do you agree?

**Comment by mschneid** [comment]
Ok I'm fine with that. Do you want to keep the factory to "simplify" the bootstrap process or go back to the 'MustacheEngineBuilder'?

**Comment by mkouba** [comment]
The latter one ;-)

**Pull request closed without merging**
